# NumPy

## What is NumPy?

NumPy (**Num**erical **Py**thon) is an open-source Python library that provides support for large, multi-dimensional homogeneous arrays and matrices, along with a collection of mathematical functions to efficiently operate on these data structures. It is the core package for scientific computing in Python.

## References

- [NumPy User Guide](https://numpy.org/doc/stable/user/index.html)

## Installation {.hide .smaller-90}

You can install NumPy using `pip`:

```bash
pip install numpy
```

Or using `conda`:

```bash
conda install numpy
```

To use NumPy, you need to import the `numpy` module:

```{.python}
import numpy as np
```

:::{.notes}
Numpy is a third-party library, so it is not included in the Python Standard Library. 
:::

## What is an array?

An array is a data structure consisting of a collection of elements. A one-dimensional array is like a list:

$$
\begin{array}{|c|c|c|c|}
\hline
1 & 5 & 2 & 0 \\
\hline
\end{array}
$$

A two-dimensional array (matrix) would be like a table:

$$
\begin{array}{|c|c|c|c|}
\hline
1 & 5 & 2 & 0 \\
\hline
8 & 3 & 6 & 1 \\
\hline
1 & 7 & 2 & 9 \\
\hline
\end{array}
$$

## NumPy Arrays {.hide}

The most important data structure defined by NumPy is the [numpy.ndarray](http://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html), which is a N-dimensional array object.

<br />
To create a NumPy array containing only zeros we use  [np.zeros](http://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html#numpy.zeros)

In [41]:
import numpy as np
a = np.zeros(3)

In [42]:
a

array([0., 0., 0.])

In [43]:
type(a)

numpy.ndarray

## These are not `list`!

NumPy arrays are very different from Python `list`.  Most importantly, the data *must be homogeneous* (all elements of the same type).



## NumPy Data Types {.hide}

NumPy provides it's own set of numeric [data types](https://numpy.org/doc/stable/reference/arrays.dtypes.html) (`dtypes`) that you use to construct arrays, such as:

- `float64`: 64-bit floating-point number
- `int64`: 64-bit integer
- `bool`: 8-bit True or False

## Default `dtype` {.hide}

If you don't specify the data type, it will default to `float64`:

In [44]:
a = np.zeros(3)
type(a[0])

numpy.float64

You can specify a data type using the `dtype` parameter:

In [45]:
a = np.zeros(3, dtype=int)
type(a[0])

numpy.int64

## Shape and Dimension

A *flat* array, is a one-dimensional array, it is neither a row vector nor a column vector. The shape attribute gives the number of elements along each axis (dimension).

In [46]:
a = np.zeros(10)
a.shape

(10,)

In this example, the shape is `(5,2)`, which means the array has 5 rows and 2 columns.

In [56]:
a = np.zeros((5,2))
a.shape

(5, 2)

## Reshapigng Arrays {.hide .smaller-85}

You can change the shape of the array in place using the `shape` attribute:

In [57]:
a.shape = (2, 5)
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

You can also use the `reshape` method, to get a new array with the shape:

In [58]:
b = a.reshape(10)
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

:::{.callout-important}
A `ValueError` will be raised if the array cannot be reshaped to the desired shape (e.g., if the number of elements in the new shape is different from the number of elements in the original array).
:::

## Creating Arrays {.hide .smaller-70}

You can create arrays from lists or tuples using the `np.array` function:

In [64]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

`np.ones` is similar to `np.zeros`, but it creates an array filled with ones:

In [59]:
a = np.ones(3)
a

array([1., 1., 1.])

`np.empty` creates arrays in memory that can later be populated with data

In [60]:
a = np.empty(3)
a

array([1., 1., 1.])

:::{.callout-warning}
The numbers in an array generated by `np.empty` are garbage values, they are values that were already in the memory location that was allocated for the array.
:::

## Creating Arrays (cont'd) {.hide .smaller-70}

`np.full` creates an array filled with a specified value:

In [61]:
a = np.full((2,2), 3)
a

array([[3, 3],
       [3, 3]])

`np.linspace` creates an array with a specified number of elements, evenly spaced between two values:

In [62]:
a = np.linspace(2, 4, 5)  # From 2 to 4, with 5 elements
a

array([2. , 2.5, 3. , 3.5, 4. ])

`np.identity` (or `np.eye`) creates a square matrix with ones on the diagonal and zeros elsewhere:

In [63]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Arrays from Files {.hide .smaller-70}

You can create arrays from files using `np.loadtxt` or `np.genfromtxt`.  The later is more flexible and can handle missing values.

<br />

Consider the following file `data.csv`:

```csv
1,2,3
4,5,6
7,8,9
```

`np.loadtxt` it will create a 2D array with the values from the file:

In [68]:
a = np.loadtxt('data.csv', delimiter=',')
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

## Indexing and Slicing {.hide .smaller-70}

You can access elements in an array using indexing and slicing, just like you would with a list:

In [75]:
a = np.linspace(0, 5, 6, dtype=int)

print(a[0]) # First element
print(a[-1]) # Last element
print(a[2:4]) # Third and fourth elements
print(a[2:]) # Everything from the third element onwards

0
5
[2 3]
[2 3 4 5]


In [80]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a[0, 0]) # First row, first column
print(a[:, 0]) # First column
print(a[0, :]) # First row
print(a[0:2, 0:2]) # First two rows and first two columns


1
[1 4 7]
[1 2 3]
[[1 2]
 [4 5]]


## Mathematical functions {.hide .smaller-70}

NumPy provides a wide range of mathematical functions that operate on arrays  To many to list here, but some of the most common are:

- Trigonometric functions: `np.sin`, `np.cos`, `np.tan`, `np.arcsin`, `np.arccos`, `np.arctan`
- Hyperbolic functions: `np.sinh`, `np.cosh`, `np.tanh`, `np.arcsinh`, `np.arccosh`, `np.arctanh`
- Sums, Products, Differences: `np.sum`, `np.prod`, `np.diff`
- Exponents and logarithms: `np.exp`, `np.log`, `np.log2`, `np.log10`

::: {.callout-info}
See the [NumPy Mathematical Functions Reference](https://numpy.org/doc/stable/reference/routines.math.html) for a complete list of functions.
:::